### ISSUE TITLE
Error while running ./setup.sh email list

### ISSUE THREAD

**Issue by GenesisAdam** [docker-mailserver/docker-mailserver#2086] opened 2021-07-15 21:42 UTC
# Subject

Other

## Description
./setup.sh email list giving errors stated below. The mailserver is installed on Synology NAS using docker and traefikV2.

``` BASH
# CODE GOES HERE
 Error: userdb lookup: connect(/var/run/dovecot/auth-userdb) failed: No such file or directory
 Error: User lookup failed: Internal error occurred. Refer to server log for more information.
/usr/local/bin/listmailuser: line 12: 1024 *  : syntax error: operand expected (error token is "*  ")
/usr/local/bin/listmailuser: line 12: 1024 *  : syntax error: operand expected (error token is "*  ")

```

**Comment by NorseGaud** [comment] 2021-07-19 17:23
@GenesisAdam , can you provide some details about your docker-compose, etc.

**Comment by GenesisAdam** [comment] 2021-07-19 18:34
> 
> 
> @GenesisAdam , can you provide some details about your docker-compose, etc.

mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail          # ${HOSTNAME}
    domainname: domainname.com  # ${DOMAINNAME}
    container_name: domainmail    # ${CONTAINER_NAME}
    networks:
      - t2_proxy
    #ports:
      #- "25:25"
      #- "143:143"
      #- "587:587"
      #- "993:993"
    volumes:
      - /volume1/docker/maildata:/var/mail
      - /volume1/docker/mailstate:/var/mail-state
      - /volume1/docker/maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /volume1/docker/mailserver/certs:/certs
      - /volume1/docker/mailserver/certs/cert:/var/mail-state/manual-ssl/cert
      - /volume1/docker/mailserver/certs/key:/var/mail-state/manual-ssl/key
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/var/mail-state/manual-ssl/cert
      - SSL_KEY_PATH=/var/mail-state/manual-ssl/key
      - POSTFIX_INET_PROTOCOLS=ipv4
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    labels:
      - "traefik.enable=true"
      - "mailserver-traefik.renew.domain=domainname.com"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
networks:
   t2_proxy:
    external: true
volumes:
  maildata:
  mailstate:
  maillogs:

**Comment by wernerfred** [comment] 2021-07-20 07:09
@GenesisAdam i fixed the style of your comment. Please be aware that we all spend our free time on this project. So please try to be as precise as possible and use/read the styling/contribution guidelines.

Here for example you should have used the bug report. You are using the server and encountered an error. That is not a general question. If you would have used the bug template it would have asked about all details that are missing right now from your side. So please be aware of this the next time you open an issue.

**Comment by NorseGaud** [comment] 2021-07-20 11:39
@GenesisAdam , did you look at the logs to see if there are any errors?

**Comment by GenesisAdam** [comment] 2021-07-20 21:58
@wernerfred , I am so sorry about not posting in the appropriate format. I am not used to posting on github. Thanks for your help in reformatting my post.

**Comment by georglauterbach** [comment] 2021-07-21 09:40
This is a mismatch of the version of DMS and the `setup.sh` Script. Try updating the script, if that doesn’t help, try updating DMS too.

**Comment by georglauterbach** [comment] 2021-07-21 09:42
Closing this as a likely duplicate of #2038

**Closed by georglauterbach** 2021-07-21 09:42 UTC
Labels: kind/bug, meta/help wanted, meta/needs triage, meta/template not used, orchestrator/compose, priority/low

**Comment by keith24** [comment] 2021-09-16 16:49
I just got this error on a fresh install of the latest DMS image and master branch version of `setup.sh`.  

Should I post server logs here or open a new issue?  Or does someone want to try to reproduce it first?  

It says `Refer to server log for more information.` but my logs dir only has `clamav.log` and `freshclam.log`.

**Comment by casperklein** [comment] 2021-09-16 18:43
> open a new issue?

This.

**Comment by keith24** [comment] 2021-09-16 21:50
On second thought... I don't think it's worth fixing.  

The `setup.sh email` commands still work; they just throw errors.  

Also, I haven't tried v10.2 yet so maybe this is resolved when the script comes with the image.  If I have this trouble with 10.2 or higher, using the `setup.sh` from inside the container, I'll open a new issue.  

Until then, here is a way to hide the errors from `email list`:

```sh
./setup.sh email list | egrep '^\* ' | awk '{print $2}'
```
