### ISSUE TITLE
[BUG] rspamd forgets it learned spam and ham when docker-compose down and up is issued

### ISSUE THREAD

**Issue by hanscees** [docker-mailserver/docker-mailserver#3138] opened 2023-03-01 19:30 UTC
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

rspamd will not easily learn to recognize spam

### What happened and when does this occur?

I have trained rspamd with two email-folders containing spam or ham like so

First get stats on learned spam
`docker exec -it mailserver sh
rspamc stat

Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 1; users: 1; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 6; users: 1; languages: 0
Total learns: 7
`

Then I train rspamd with a folder full of spam, and a folder full of spam

`rspamc learn_spam /var/mail/fanscees.com/hanscees/.spam/cur
rspamc stat
Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 413; users: 1; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 6; users: 1; languages: 0
Total learns: 419
`
Same with ham training 
`
rspamc learn_ham /var/mail/hanscees.com/hanscees/.Ham/cur
rspamc stat
Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 413; users: 1; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 354; users: 1; languages: 0
Total learns: 767
`

I also have enabled that rspamd learns from users when they move email in and out the inbox.junk folder: see attached txt script 
[rspamd-patches.txt](https://github.com/docker-mailserver/docker-mailserver/files/10864574/rspamd-patches.txt)

Problem is now, after doing a docker-compose down, all learned material seems gone.

`docker-compose down
docker-compose up -d
Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 0; users: 0; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 0; users: 0; languages: 0
Total learns: 0
`

I think something should be added to the mailstate that is preserved, but no idea what. 

### What did you expect to happen?

I expect learned spam to persist over a reset of the docker image

### How do we replicate the issue?

do what I did above

### DMS version

1301

### What operating system is DMS running on?

Linux

### Which operating system version?

photon 4

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:edge
    #image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: fanscees.net
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "995:995"  # pop3 (implicit TLS)
      - "110:110"  # pop3 (implicit TLS)
    volumes:
      #- etc:/etc
      - maildata:/var/mail/
      - mailstate:/var/mail-state/
      - log:/var/log/
      - Tconfig:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ssl:/tmp/ssl
    restart: always
    stop_grace_period: 1m
    environment:
     # If you need SSL connection, you can provide your own certificates
     - SSL_TYPE=manual
     - SSL_CERT_PATH=/tmp/ssl/fullchain.pem
     - SSL_KEY_PATH=/tmp/ssl/privkey.pem
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
volumes:
  maildata:
  mailstate:
  Tconfig:
  log:
  ssl:
```

### Other relevant information

I have also enabled the auto-learn rule on spam form your documentation

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment] 2023-03-01 23:11
This is something @georglauterbach can probably answer. If the training is only stored in Redis, [we don't persist that to disk](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/startup/setup.d/mail_state.sh#L29) (_Redis is an in-memory store, but IIRC, there are some options to leverage a file on disk when suitable_).

There was support recently merged for [using your own external redis instance](https://github.com/docker-mailserver/docker-mailserver/pull/3132), if you have that setup and only bring down the DMS container, then that might confirm if it's an issue with how we're using Redis. Otherwise, wait until @georglauterbach chimes in as he probably has a better idea of the cause :sweat_smile:

**Comment by georglauterbach** [comment] 2023-03-01 23:31
I noticed this as well, and I will look into it after my current PRs are merged.

**Comment by hanscees** [comment] 2023-03-03 09:53
I couldnt help myself and tried to fix form the userpatch script. 
Alas it massively failed. 
To change how redis starts you need to change supervisorctl and that probably starts before the user script. 
So you have to reload it and then many things go wrong.

So I learned a lot about the upstart scripts :)

The changes I tried are below, but they fail so dont try this at home. Perhaps when George later on picks this up they might help. 

This is what I added to the userscript. 

```
### so adjusting redis files should be like
#adjust /var/lib where persistent database will be
mkdir /var/mail-state/lib-redis  # only once
ln -s /var/mail-state/lib-redis /var/lib/redis

#change redis config file
sed -i  "s|bind 127.0.0.1 ::1|bind 127.0.0.1|" /etc/redis/redis.conf
sed -i  "s|daemonize yes|daemonize no|" /etc/redis/redis.conf
## it might also need a change in the config part about supervised

# adjust supervisor-app.conf redis command
sed -i  "s|--daemonize no --bind 127.0.0.1 --port 6379 --loglevel warning|/etc/redis/redis.conf --daemonize no|" /etc/supervisor/conf.d/supervisor-app.conf

# this fails dont do it
#supervisorctl reload
#supervisorctl stop redis
#supervisorctl start redis
```

also I dont know why redis and rspamd do not log to /var/log. Makes it harder to troubleshoot, but perhaps there is a gooid reason for it I dont know.

**Comment by georglauterbach** [comment] 2023-03-03 12:39
Thanks for the guidance! I think I found a solution. Will provide a PR.

**Comment by polarathene** [comment] 2023-03-03 13:16
> #adjust /var/lib where persistent database will be
> mkdir /var/mail-state/lib-redis  # only once
> ln -s /var/mail-state/lib-redis /var/lib/redis

That could be added [here](https://github.com/docker-mailserver/docker-mailserver/blob/9e2f96448ad4f5afd897621c54a731bbb18e12bb/target/scripts/startup/setup.d/mail_state.sh#L29) if it makes sense to, as mentioned before.

> sed -i  "s|bind 127.0.0.1 ::1|bind 127.0.0.1|" /etc/redis/redis.conf
> sed -i  "s|daemonize yes|daemonize no|" /etc/redis/redis.conf

https://github.com/docker-mailserver/docker-mailserver/blob/9e2f96448ad4f5afd897621c54a731bbb18e12bb/target/supervisor/conf.d/supervisor-app.conf#L115

You're replacing config shipped by the `redis-server` package (no changes from us) to only bind to IPv4 address, and avoid running as a daemon (_so supervisor is happy by getting the process running in the foreground_).

However these were already configured explicitly via the args in the supervisor config, which you then replace with a config path and the daemonize opt-out again for some reason?

I found that a bit bizarre, so I looked at Redis docs and saw the following:

- https://redis.io/docs/management/config/#passing-arguments-via-the-command-line
- https://redis.io/docs/getting-started/#redis-persistence
- https://redis.io/docs/getting-started/faq/#background-saving-fails-with-a-fork-error-on-linux
- https://redis.io/docs/management/persistence/

**`redis-server -h`:**

```
Usage: ./redis-server [/path/to/redis.conf] [options]
       ./redis-server - (read config from stdin)
       ./redis-server -v or --version
       ./redis-server -h or --help
       ./redis-server --test-memory <megabytes>

Examples:
       ./redis-server (run the server with default conf)
       ./redis-server /etc/redis/6379.conf
       ./redis-server --port 7777
       ./redis-server --port 7777 --replicaof 127.0.0.1 8888
       ./redis-server /etc/myredis.conf --loglevel verbose

Sentinel mode:
       ./redis-server /etc/sentinel.conf --sentinel
```

In particular I want to quote from the `getting-started/#redis-persistence` link:

>  if you start Redis with the default configuration, Redis will spontaneously save the dataset only from time to time (for instance after at least five minutes if you have at least 100 changes in your data),
> so if you want your database to persist and be reloaded after a restart make sure to call the **`SAVE`** command manually every time you want to force a data set snapshot.
> Otherwise make sure to shutdown the database using the **`SHUTDOWN`** command

You're relying on that default config for persistence feature, but it's not entirely reliable given that description.
- In this scenario the 5 minutes duration isn't too much of a concern, but you do also need _at least 100 changes_ for that `SAVE` to occur.
- `supervisord` is a bit dumb in that it lacks flexibility to run commands for restart / stop, such as the mentioned `SHUTDOWN`, so if you stop the container at any point, you'll lose any changes since the last `SAVE`.

Also as per the FAQ, keep in mind that if the Redis DB does get large, it needs twice the amount of memory to perform the `SAVE`, which it should not use due to CoW nature of the fork, but by default will expect the same amount of used memory as available unless you set `vm.overcommit_memory=1` (_not a redis setting, a sysctl one, which may not be permitted in Docker default capabilities? It's a kernel setting, so supposedly if you set this on the host, it should also be visible from the container, not something we can do other than document awareness for users_)

---

> also I dont know why redis and rspamd do not log to /var/log. Makes it harder to troubleshoot, but perhaps there is a gooid reason for it I dont know.

I will take a random guess that it wasn't considered when the feature support was being added into DMS. There was a lot to review beyond that, and I don't have time to be as thorough as I'd like :sweat_smile: (_I'd have missed that anyway though_)

Logging has recently been investigated and may be improved in future.

Redis should already have default config to log (at least when you specified the sample config):

```
# Specify the log file name. Also the empty string can be used to force
# Redis to log on the standard output. Note that if you use standard
# output for logging but daemonize, logs will be sent to /dev/null
logfile /var/log/redis/redis-server.log
```

This logs as expected when used (_I didn't `--daemonize no` or use `supervisorctl`_).

With current supervisor config for Redis, the command is run in foreground and written by supervisor to the log `/var/log/supervisor/redis.log`, all looks to be working there too, perhaps you checked the wrong location?

Redis can, and perhaps should (_along with other services we run_) be configured to forward logs to syslog instead, which can be done in `/etc/rsyslog.d` by adding a conf file for the service. Setting up Redis with syslog is described online such as [here](https://betterstack.com/community/guides/logging/how-to-start-logging-with-redis/). Personally probably fine to leave supervisor handling it as-is, unless someone wants to filter the logs elsewhere, but I think that'll be better suited if we adopt Vector instead of the current Rsyslog.

[Rspamd is the same](https://rspamd.com/doc/configuration/logging.html) for logging support.

**Comment by georglauterbach** [comment] 2023-03-03 15:43
PS for @hanscees: I will probably also provide a PR that adds functionality you proposed, so Rspamd can learn ham/spam by moving mails from/to the spam folder (via Sieve). This will probably not go into v12.0.0. though; rather v12.1.0.

**Comment by hanscees** [comment] 2023-03-03 15:54
> However these were already configured explicitly via the args in the supervisor config, which you then replace with a config path and the daemonize opt-out again for some reason?

The whole point is to get redis to save what it learns from rspamd learning spam and ham. To do that I used the config file, since you need a lot of options for that.
The database does not get saved very often but that's not a big deal, it does save by default when shutting down.
It saves the database in mail-state with the changes and link command.

**Comment by georglauterbach** [comment] 2023-03-03 16:00
#3143 will resolve this issue. You can have a look at the changes I made there to get an idea what is required. You were already very close @hanscees, thanks for your insights!

**Comment by hanscees** [comment] 2023-03-03 16:02
> With current supervisor config for Redis, the command is run in foreground and written by supervisor to the log `/var/log/supervisor/redis.log`, all looks to be working there too, perhaps you checked the wrong location?

In the beginning I did :)
But the point is to let it log somewhere where others logs are too. That's /var/log. 
These are commonly saved if you use docker and make a docker volume for it. Syslog could be used or some other log. I prefer Syslog for all normal logging cause it's easier to see how postfix and it's subprocesses run together, but perhaps there are good reasons to have separate logs. 

My point in using the redis config file was not for logging, but to let the database persist. So when you let rspamd learn from a folder full of ham and/or a folder full of spam the learned is remembered and your anti-spam improves.

**Comment by hanscees** [comment] 2023-03-03 16:03
> PS for @hanscees: I will probably also provide a PR that adds functionality you proposed, so Rspamd can learn ham/spam by moving mails from/to the spam folder (via Sieve). This will probably not go into v12.0.0. though; rather v12.1.0.

What is a PR? I am afraid I don't know 😫

**Comment by georglauterbach** [comment] 2023-03-03 16:06
PR is the abbreviation for [Pull Request](https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) :)

**Comment by polarathene** [comment] 2023-03-03 23:15
> But the point is to let it log somewhere where others logs are too. That's /var/log.

Usually, but we use supervisord to manage all the services that we run, those unfortunately have to be run via foreground (_which has caused some annoyances_) and we have a common location for all the logs received that way into the `/var/log/supervisor` location.

It's non-standard vs not using supervisord, but it does make sense for all the services we directly manage to co-locate the logs there.

That said, it's not consistent. Some of the services are configured to use syslog instead, which is additionally configured to redirect and filter logs to various files / locations.

syslog has the benefit of being able to group logs into the same log file (_which we have with `/var/log/mail/mail.log` that you see displayed in the console if not running `docker compose up` with `-d`_), prior to that stage beyond logs having categories (aka facilities) like `mail`, the logs get tagged by the service name and log level metadata, all that is useful if you need more control over the logs for a deployment / audit.

---

> These are commonly saved if you use docker and make a docker volume for it.

That's still the case, all log files are still written into `/var/log`, just different location as mentioned. The mail log containing logs from various services involved in mail is a common practice AFAIK.

> I prefer Syslog for all normal logging cause it's easier to see how postfix and it's subprocesses run together, but perhaps there are good reasons to have separate logs.

I don't think that's specific to syslog per se.

It would be good for rspamd and redis services to also use syslog. I'd like to eventually bring in Vector which is nicer to have when more control over how your logs are managed is needed.

---

> My point in using the redis config file was not for logging, but to let the database persist.

I understand. I replied around 2am before sleeping and was mostly wanting to document concerns.

There was gotchas to keep in mind, and using the default config IIRC isn't advised, but I get that you did for convenience to test that persistence resolved the issue :+1:

**Closed** 2023-03-04 09:45 UTC
Labels: kind/bug, priority/medium, area/scripts, area/configuration (file), service/rspamd

**Comment by hanscees** [comment] 2023-03-04 09:56
Does this mean I can now test it if I pull down edge? 
And a new  .env file?

**Comment by georglauterbach** [comment] 2023-03-04 09:59
> Does this mean I can now test it if I pull down edge? 
> 
> And a new  .env file?

You probably need to wait a few minutes for the image being available, but yes! Moreover, there is _no_ new ENV you need to set explicitly (as this behaviour is the default), if you use `ONE_DIR=1` (which again is a default) and you have a volume mounted to `/var/mail-state/`.
