### ISSUE TITLE
[FR] add the project on the wikipedia page

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#2718] opened 2022-08-10 20:33 UTC
# Feature Request

## Context

https://en.wikipedia.org/wiki/Comparison_of_mail_servers

### Is your Feature Request related to a Problem?

No

### Describe the Solution you'd like

Someone should document it

### Are you going to implement it?

No

### What are you going to contribute??

Nothing

### Alternatives you've considered

None

### Who will that Feature be useful to?

curious comparing people

### What have you done already?

nothing

**Comment by polarathene** [comment] 2022-08-10 22:31
DMS provides the integration / glue with scripts and Docker to setup a mail-server (_via Postfix and Dovecot services that you'll find listed in the Wikipedia article_).

However, we are not a mail-server software in itself, as you'll notice none of the alternative solutions to DMS (MailCow, Mailu, Mail-in-a-box, iRedMail, etc) are listed in that article, and for good reason (_they practically all use a similar stack that we do, with Postfix and Dovecot_).

---

If you'd like to, a more appropriate location is in [this related Wikipedia article](https://en.wikipedia.org/wiki/List_of_mail_server_software#Mail_server_packages), where you'll see many of the projects similar to DMS I mentioned are listed in the "Mail server packages" section. Feel free to submit an edit to the page to add us if you like.

I've seen other various websites/projects that DMS could be listed on as well, the community is welcome to engage with the resource owners to include us in their lists.

Closing as this is not really relevant to DMS (eg: not a bug or feature for us to implement).

**Closed by polarathene** 2022-08-10 22:31 UTC
Labels: meta/needs triage, priority/low
