### ISSUE TITLE
bug report: Instructions in the documentation seem to be out of date

### ISSUE THREAD

**Issue by fawzibr** [docker-mailserver/docker-mailserver#3409] opened 2023-06-27 20:55 UTC
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Tried to install following the documentation page ([Usage](https://docker-mailserver.github.io/docker-mailserver/latest/usage/)):

```
**Get All Files**
Issue the following commands to acquire the necessary files:

DMS_GITHUB_URL="https://github.com/docker-mailserver/docker-mailserver/blob/latest"
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
```

Those files give me a 404 error. 

Using https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/ works, also there is no docker-compose.yml, just a compose.yml

### 👟 Reproduction Steps

DMS_GITHUB_URL="https://github.com/docker-mailserver/docker-mailserver/blob/latest"
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"

### 🐋 DMS Version

latest

### 💻 Operating System and Architecture

Synology

**Comment by casperklein** [comment] 2023-06-27 22:39
Thanks for reporting, this issue has already been addressed.

Duplicate of: #3375 #3394 
Already fixed: #3337

To see the most current version of the documentation, you have to select "edge" in the top left drop down menu.

**Closed** 2023-06-27 22:41 UTC
Labels: meta/needs triage, kind/bug/report
