### ISSUE TITLE
bug report: ClamAV doesn't start after update

### ISSUE THREAD

**Issue by Nebucatnetzer** [docker-mailserver/docker-mailserver#4083] opened 2024-06-20 05:36 UTC
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After updating to 14.0.0 didn't want to start anymore

Could this be a problem with ARM64?

I unfortunately don't have much more logs as I disabled ClamAV while investigating this issue and only enabled debugging afterwards: https://github.com/docker-mailserver/docker-mailserver/issues/4082

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

NixOS 24.05 ARM64

### 📜 Relevant log output

```Text
un 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,389 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,429 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,479 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,532 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,595 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,695 WARN exited: clamav (exit status 1; not expected)
```

**Comment by polarathene** [comment] 2024-06-20 23:31
Does a v14 image work with ClamAV disabled? Given the linked issue, the ClamAV concern might be a side-effect to the real problem.

**Comment by polarathene** [comment] 2024-06-21 00:31
Closing as identified the cause.

- `ONE_DIR=0` + `/var/mail-state` volume mount (NFS) were used. v14 removed the `ONE_DIR` ENV as it was redundant, since mounting `/var/mail-state` implies the expectation of `ONE_DIR=1` to use that location.
- ClamAV state was now attempting to be persisted to `/var/mail-state`, but due to NFS usage (_which DMS does not support officially_), failures ensued.

**Closed by polarathene** 2024-06-21 00:31 UTC
Labels: meta/needs triage, kind/bug/report

**Comment by okainov** [comment] 2024-07-09 14:51
>Closing as identified the cause.

Thanks for investigation, but I'm not sure I understand what do I do with this...

I had old installation of docker-mailserver from version 7 which I decided to upgrade today. Did every sequential upgrade to every new major version, and it was fine until 14.0 where I'm getting this error.

Relevant info from my compose (which is intact from the old version)

```yaml
services:
 mail:
    build:
      context: docker-mailserver
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt/:/etc/letsencrypt/
    - ./postfix_sql/:/etc/postfix/sql/

volumes:
  maildata:
  mailstate:
  maillogs:
```

I'm not using any "ONE_DIR"...

**Comment by polarathene** [comment] 2024-07-09 23:00
> I'm not using any "ONE_DIR" nor NFS shares...

You cited using NFS here: https://github.com/docker-mailserver/docker-mailserver/issues/4082#issue-2363554464

> _The files live on a NFS share._

Likewise in [my response there](https://github.com/docker-mailserver/docker-mailserver/issues/4082#issuecomment-2181770792) I reference your external nix config for the separate `.env` file which did have `ONE_DIR=0` (opt-out), a misconfiguration with your volume usage that was caught with the v14 upgrade since we made that ENV + volume mount combination incompatible.

---

My bad, I should have added the context of my response at the associated issue when I closed this in case anyone else arrived here, now they'd know how to troubleshoot 👍

**Comment by okainov** [comment] 2024-07-10 05:59
>EDIT: Whoops my bad, you aren't the same user 😆

Yeah :)
