### ISSUE TITLE
Not able to start docker image

### ISSUE THREAD

**Issue by nishiths23** [docker-mailserver/docker-mailserver#2707] opened 2022-07-30 10:50 UTC
# Tried following the getting started guide but I keep getting these logs:

Other

## Description

``` BASH
mailserver | 2022-07-30 16:12:19,504 INFO exited: dovecot (exit status 89; not expected)
mailserver | 2022-07-30 16:12:19,504 DEBG received SIGCHLD indicating a child quit
mailserver | 2022-07-30 16:12:19,505 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mailserver | 2022-07-30 16:12:19,507 INFO spawned: 'dovecot' with pid 2613
mailserver | 2022-07-30 16:12:19,534 DEBG 'dovecot' stderr output:
mailserver | Error: bind(/var/spool/postfix/private/auth) failed: Invalid argument
mailserver | 
mailserver | 2022-07-30 16:12:19,534 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mailserver | 2022-07-30 16:12:19,535 DEBG 'dovecot' stderr output:
mailserver | Error: service(auth): net_listen_unix(/var/spool/postfix/private/auth) failed: Invalid argument
mailserver | Fatal: Failed to start listeners
```

Steps followed

1. Ran this command
```bash
DMS_GITHUB_URL='https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master'
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
wget "${DMS_GITHUB_URL}/setup.sh"
chmod a+x ./setup.sh
```
2. Added a new email using
```BASH
./setup.sh email add <user@domain> [<password>]
```

3. Created DKIM keys. 
```BASH
./setup.sh [-Z] config dkim
```

3. Ran the image
```BASH
docker-compose up -d mailserver
```

But it did not run, gives the above logs

**Comment by casperklein** [comment] 2022-07-30 11:55
Following the steps you mentioned, DMS starts fine for me.

What does your docker-compose.yml looks like? Did you change anything to the default configuration, especially SSL settings?
If so, check if the certificate is correctly mounted and the correct path is configured. `var/spool/postfix/private/auth` isn't created by Dovecot, [when there are certificate issues](https://serverfault.com/a/732509).

**Comment by nishiths23** [comment] 2022-07-30 16:40
I did not update anything. I found this repo, because I was looking for something just like this and started by going through the readme and just followed the first time steps. I would like to add that you guys have done a great work, huge respect for everyone who contributed for this project, I just hope I can run and deploy it. Once that is done would also love to contribute

Screenshot of docker-compose file:

<img width="1186" alt="Screenshot 2022-07-30 at 10 06 41 PM" src="https://user-images.githubusercontent.com/16319917/181932635-a0459945-9b2d-4489-9216-74495641b981.png">

Is there any extra step that I missed?

**Comment by polarathene** [comment] 2022-07-30 22:25
What OS are you running? (_and distro + version and kernel if linux_)

What version is `docker-compose`?

Is docker configured to run as rootless, or is it running as root (default)?

---

These type of issues with `/var/spool/postfix/private/auth` have been happening more often for users, but it's unclear why as none of the maintainers have been able to reproduce.

**Comment by nishiths23** [comment] 2022-07-31 07:13
Yes I am using macOS-12.4 production version

Docker compose version:
```bash
Docker Compose version v2.6.1
```

So I did not do any extra steps while installing docker, so if the default is root then, root it is.

**Comment by polarathene** [comment] 2022-07-31 08:49
> Yes I am using macOS-12.4 production version

Great, I believe that's likely the issue then. Here are some related issues around `/var/spool/postfix/private/auth`:

- https://github.com/docker-mailserver/docker-mailserver/issues/2630
- https://github.com/docker-mailserver/docker-mailserver/issues/2700
- https://github.com/docker-mailserver/docker-mailserver/issues/2678

I made some efforts to help investigate but the reporters stopped looking into it. I don't think any of the regular maintainers use macOS or have access to a mac system to investigate further unfortunately.

Chances are this is something specific to the macOS environment or it's implementation for Docker. You normally wouldn't deploy DMS to a mac server, so for local testing perhaps try running Docker in a linux VM guest. Chances are that will work.

**Comment by polarathene** [comment] 2022-07-31 08:50
Could you also confirm if this is running off M1/M2 chip? (Recent mac devices)

**Comment by nishiths23** [comment] 2022-07-31 10:02
😅 Ok so this is unexpected but makes sense. Sure will use a Linux VM.

I am using intel Mac right now.

**Comment by ecker00** [comment] 2022-08-31 05:35
Think it's relevant to keep this issue open, as it still seems to be a problem when running on a MacOS server.

**Comment by Ri1a** [comment] 2022-10-19 20:39
This also happens on my Apple M1 (macOS Monterey V 12.6). I also used the default docker-compose file:
```bash
mailserver  | Oct 19 22:35:03 mail dovecot: master: Fatal: Failed to start listeners
mailserver  | Oct 19 22:35:03 mail dovecot: master: Error: bind(/var/spool/postfix/private/auth) failed: Invalid argument
mailserver  | Oct 19 22:35:03 mail dovecot: master: Error: service(auth): net_listen_unix(/var/spool/postfix/private/auth) failed: Invalid argument
```

**Comment by johnmccabe** [comment] 2022-10-24 12:25
I'd hit the same on OSX 12.6 with Docker 20.10.20. Commenting out all the local volume mounts allowed the container to start as expected (it had been working for me without having to do that on Windows 11 via WSL).

(I was creating users from the command line within the container, and had to manually create the `/tmp/docker-mailserver` directory first)

**Comment by polarathene** [comment] 2022-10-24 19:09
**EDIT:** This comment is about the file having a permission error, rather than an invalid argument error, but might be relevant.

---

@johnmccabe if you are able to reproduce, it's possible a `user-patches.sh` as described recently in [this discussion](https://github.com/docker-mailserver/docker-mailserver/discussions/2846#discussioncomment-3946237) could fix the problem.

```bash
# remove old, leftover files
rm -rf /var/spool/postfix/private/auth
```

If we can get some confirmation that a workaround like that does resolve it, then we can add that to our startup scripts I think as a fix. It might be that this file is persisted to a volume mount and the container is restarted later but didn't expect this file to have persisted.

Alternatively trying `ONE_DIR=0` should also fix it (_the default is `ONE_DIR=1` for putting our mail state into a single volume location, instead of many mounts for each service_)

**Comment by johnmccabe** [comment] 2022-10-24 20:03
@polarathene makes sense, I'll dig into it and report back, had hit problems with how Docker for mac handles sockets in the past when trying to SSH Agent forwarding working.

**Comment by georglauterbach** [comment] 2023-03-19 11:11
This issue should actually be resolved on `:edge`. Can someone please verify?

**Comment by polarathene** [comment] 2023-03-19 22:00
> Can someone please verify?

We already have someone who had related issues from Podman AFAIK due to chroot capability being disabled by default or something. Probably better to wait until Dovecot and PostSRSd have also opted out of chroot.

I'm a bit behind schedule but plan to get to that this week.

**Comment by georglauterbach** [comment] 2023-04-19 09:11
Should be resolved on `:edge`. Closing this now. If someone still has this issue, please ping me here.

**Closed by georglauterbach** 2023-04-19 09:11 UTC
Labels: service/dovecot, os/macOS, issue/limited support, kind/bug/report, bug/confirmed, bug/solution verified
