### ISSUE TITLE
Docker mail server update broke

### ISSUE THREAD

**Issue by gartia** [docker-mailserver/docker-mailserver#3214] opened 2023-04-01 20:47 UTC
# Subject
I have a question about docker-mailservers image.

## Description
I had docker mail server just running for a long time and then we had our server box shut down for the first time in a about a year. The image redownloaded when i restarted docker and i thought that was odd and now i can't start my mail server. I'm unfortunately away from office so trying to fix this has been awful. I'm getting the error below with an empty docker-data and the old docker-data. I redid the docker-compose. I'm not entirely sure what is going on with this error.
``` BASH
# CODE GOES HERE
mailserver    | rm: cannot remove '/var/spool/postfix/usr': Directory not empty
mailserver    | rm: cannot remove '/var/lib/amavis': Directory not empty
mailserver    | chgrp: cannot access '/var/mail-state/spool-postfix/maildrop': No such file or directory
mailserver    | chgrp: cannot access '/var/mail-state/spool-postfix/public': No such file or directory
mailserver    | chown: cannot access '/var/mail-state/spool-postfix/dev': No such file or directory
mailserver    | chown: cannot access '/var/mail-state/spool-postfix/etc': No such file or directory
mailserver    | chown: cannot access '/var/mail-state/spool-postfix/lib': No such file or directory
mailserver    | chown: cannot access '/var/mail-state/spool-postfix/pid': No such file or directory
mailserver    | [   INF   ]  Starting daemons
mailserver    | [   INF   ]  **domain snipped** is up and running
mailserver    | Apr  1 20:43:02 mail dovecot: master: Error: bind(/var/spool/postfix/private/auth) failed: No such file or directory
```

**Comment by georglauterbach** [comment] 2023-04-01 23:15
Because you have given absolutely zero information about which version you used, which version is running now, and so on and so forth, there is nearly zero information I can give you now to help.

The log indicates you're using `:edge`, but this is just a guess.

Please open a new issue with the bug report template, so we can properly assist in case this is a bug with the upcoming release of v12.0.0.

**Comment by polarathene** [comment] 2023-04-05 01:50
> The log indicates you're using `:edge`, but this is just a guess.

I think they'd be using `latest` (`11.3.1`) due to the final error from dovecot with the `private/auth` socket, we changed that for v12, now available in `:edge`:

https://github.com/docker-mailserver/docker-mailserver/blob/637d27efc72e11b50da69b262943d3ca29aea14f/target/dovecot/10-master.conf#L91

@gartia should know better with Docker not to rely on `:latest` tag because it can cause this issue of implicitly upgrading through major versions encountering breaking changes.

> I'm unfortunately away from office so trying to fix this has been awful.
> I'm getting the error below with an empty docker-data and the old docker-data.
> I redid the docker-compose. I'm not entirely sure what is going on with this error.

Since you're very likely using `:latest` tag, it's probably safe to say these attempts involve `docker-compose up` + `Ctrl + C` instead of `docker-compose down`?

If I am correct, and you're using this workflow, either invoke `down` afterwards before `up`, or use `docker-compose up --force-recreate` and only then will it create a new container without any previous runtime state inside.

Our image makes many changes to start based on the assumption of a known good state. It is not designed to revert changes perfectly when config changes, so you should ensure that internal state from a previous container run is not present by re-creating a new container instance of the image.

In a week `v12` will be released, if you're going through the trouble of upgrading now, I would advise updating to v12 once it's available as it contains various improvements / fixes.

---

Closing as this is not a bug and user has not responded since.

**Closed by polarathene** 2023-04-05 01:50 UTC
Labels: meta/needs triage, meta/help wanted, kind/question, issue/no template - no support
