### ISSUE TITLE
 bug report: catch-all takes all incoming emails

### ISSUE THREAD

**Issue by githubX82jKm** [docker-mailserver/docker-mailserver#3594] opened 2023-10-22 10:01 UTC
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Catchall-Address catches also E-Mails for accounts!

### 👟 Reproduction Steps

Define E-Mail accounts:
setup email add catchall@domain.tld
setup email add test@domain.tld

Define an alias for catch all:
setup alias add @domain.tld catchall@domain.tld

Send an E-Mail to test@domain.tld

Expected behavior: Account test@domain.tld receives E-Mail
What happens: E-Mail is delivired to catchall@domain.tld

Only solution for me was to add an alias "example@domain.tld example.domain.tld" **manually** in postfix-virtual.cf!

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Ubuntu 22.04 LTS

**Comment by casperklein** [comment] 2023-10-23 21:23
Duplicate of https://github.com/docker-mailserver/docker-mailserver/issues/3408

**Closed by casperklein** 2023-10-23 21:23 UTC
Labels: meta/needs triage, kind/bug/report
