### ISSUE TITLE
bug report: smtp; 550 5.1.1 Recipient address rejected: User unknown in local recipient table (failed)

### ISSUE THREAD

**Issue by weatheralex1** [docker-mailserver/docker-mailserver#4196] opened 2024-09-24 22:54 UTC
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I have tried many many many different ways to fix this. I should be able to receive email at `admin@mail.nextcloud.alexanderwasson.dev` I get the same error every time. I can send but not receive.

I tried creating a `postfx-configuation.cf` file but then I got a separate error.

### 👟 Reproduction Steps

Use subdomains? I honestly have no clue. Hasn't worked since I set it up.

### 🐋 DMS Version

14.0.0

### 💻 Operating System and Architecture

Ubuntu 22.04.5 LTS x86_64 

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.nextcloud.alexanderwasson.dev
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc/letsencrypt/:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
2024-09-24T18:27:13.113214-04:00 mail postfix/postscreen[1526]: CONNECT from [17.57.155.17]:50217 to [172.18.0.2]:25
2024-09-24T18:27:19.114111-04:00 mail postfix/postscreen[1526]: PASS NEW [17.57.155.17]:50217
2024-09-24T18:27:19.810400-04:00 mail postfix/smtpd[1536]: connect from qs51p00im-qukt01072702.me.com[17.57.155.17]
2024-09-24T18:27:20.153231-04:00 mail postfix/smtpd[1536]: Anonymous TLS connection established from qs51p00im-qukt01072702.me.com[17.57.155.17]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
2024-09-24T18:27:20.295927-04:00 mail postfix/trivial-rewrite[1542]: warning: do not list domain mail.nextcloud.alexanderwasson.dev in BOTH mydestination and virtual_mailbox_domains
2024-09-24T18:27:21.460637-04:00 mail policyd-spf[1544]: : prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=17.57.155.17; helo=qs51p00im-qukt01072702.me.com; envelope-from=alexanderwasson@icloud.com; receiver=mail.nextcloud.alexanderwasson.dev 
2024-09-24T18:27:22.187009-04:00 mail postfix/smtpd[1536]: NOQUEUE: reject: RCPT from qs51p00im-qukt01072702.me.com[17.57.155.17]: 550 5.1.1 <admin@mail.nextcloud.alexanderwasson.dev>: Recipient address rejected: User unknown in local recipient table; from=<alexanderwasson@icloud.com> to=<admin@mail.nextcloud.alexanderwasson.dev> proto=ESMTP helo=<qs51p00im-qukt01072702.me.com>
2024-09-24T18:27:22.261287-04:00 mail postfix/smtpd[1536]: disconnect from qs51p00im-qukt01072702.me.com[17.57.155.17] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
```

**Comment by polarathene** [comment] 2024-09-24 23:28
> `Recipient address rejected: User unknown in local recipient table`

Your problem is because you assign email address to the same FQDN as DMS hostname. See [FAQ](https://docker-mailserver.github.io/docker-mailserver/v14.0/faq/#can-i-use-a-nakedbare-domain-ie-no-hostname).

`mail` subdomain is only intended as DNS records to point to DMS. Inside the container it is used as mail domain for system services to send notifications. Not intended for you to use for your own mail accounts. Follow the FAQ link to disable internal mail if you consider that acceptable.

**Actual fix:**
- Before: `admin@mail.nextcloud.alexanderwasson.dev`
- After: `admin@nextcloud.alexanderwasson.dev`

Create your mail account correctly and that will work. Remember that DMS only needs TLS certificate for the `hostname` you configure, the mail account domains you use with `setup email add` are not relevant for TLS, but they are for DNS (_MX records that point to DMS `hostname`_).

---

Closing as not a bug.

**Closed** 2024-09-24 23:30 UTC
Labels: area/documentation, issue/duplicate, issue/(likely) user-related misconfiguration, kind/bug/report

**Comment by weatheralex1** [comment] 2024-09-25 00:29
Thank you very much! I am very new to docker, I'm used to using snap. That worked. I'm very sorry for not being smart, I misunderstood.
