### ISSUE TITLE
I cannot success run the mailserver docker.

### ISSUE THREAD

**Issue by jasonbohan** [docker-mailserver/docker-mailserver#2520] opened 2022-04-01 09:57 UTC
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

I typed in 'docker-compose up -d ',the container always restart.It cannot used.I put the ssl file in the /opt/mailserver/ssl
my docker-compose.yml

version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: yuzhongit.com
    env_file: mailserver.env
    dns: 223.5.5.5
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "110:110"
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /opt/mailserver/mail-data/:/var/mail/
      - /opt/mailserver/mail-state/:/var/mail-state/
      - /opt/mailserver/mail-logs/:/var/log/mail/
      - /opt/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /opt/mailserver/ssl:/tmp/ssl:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
 
part of mailserver.env files 
``` BASH
# CODE GOES HERE

# Please read [the SSL page in the documentation](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl) for more information.
#
# empty => SSL disabled
# letsencrypt => Enables Let's Encrypt certificates
# custom => Enables custom certificates
# manual => Let's you manually specify locations of your SSL certificates for non-standard cases
# self-signed => Enables self-signed certificates
SSL_TYPE=manual

# These are only supported with `SSL_TYPE=manual`.
# Provide the path to your cert and key files that you've mounted access to within the container.
SSL_CERT_PATH=/tmp/ssl/mail.yuzhongit.com_chain.crt
SSL_KEY_PATH=/tmp/ssl/mail.yuzhongit.com_key.key
# Optional: A 2nd certificate can be supported as fallback (dual cert support), eg ECDSA with an RSA fallback.
# Useful for additional compatibility with older MTA and MUA (eg pre-2015).
SSL_ALT_CERT_PATH=
SSL_ALT_KEY_PATH=
```

``` BASH
# CODE GOES HERE
[root@host-10-0-0-107 mailserver]# docker-compose logs -f
Attaching to mailserver
mailserver    | [ TASKLOG ]  Welcome to docker-mailserver 10.5.0
mailserver    | [ TASKLOG ]  Initializing setup
mailserver    | [[ TASKS ]]  Registering functions
mailserver    | [[  INF  ]]  _check_hostname() registered
mailserver    | [[  INF  ]]  _setup_supervisor() registered
mailserver    | [[  INF  ]]  _setup_default_vars() registered
mailserver    | [[  INF  ]]  _setup_file_permissions() registered
mailserver    | [[  INF  ]]  _setup_dovecot() registered
mailserver    | [[  INF  ]]  _setup_dovecot_dhparam() registered
mailserver    | [[  INF  ]]  _setup_dovecot_quota() registered
mailserver    | [[  INF  ]]  _setup_dovecot_local_user() registered
mailserver    | [[  INF  ]]  _setup_dnsbl_disable() registered
mailserver    | [[  INF  ]]  _setup_dkim() registered
mailserver    | [[  INF  ]]  _setup_ssl() registered
mailserver    | [[  INF  ]]  _setup_docker_permit() registered
mailserver    | [[  INF  ]]  _setup_mailname() registered
mailserver    | [[  INF  ]]  _setup_amavis() registered
mailserver    | [[  INF  ]]  _setup_dmarc_hostname() registered
mailserver    | [[  INF  ]]  _setup_postfix_hostname() registered
mailserver    | [[  INF  ]]  _setup_dovecot_hostname() registered
mailserver    | [[  INF  ]]  _setup_postfix_smtputf8() registered
mailserver    | [[  INF  ]]  _setup_postfix_sasl() registered
mailserver    | [[  INF  ]]  _setup_postfix_sasl_password() registered
mailserver    | [[  INF  ]]  _setup_security_stack() registered
mailserver    | [[  INF  ]]  _setup_postfix_aliases() registered
mailserver    | [[  INF  ]]  _setup_postfix_vhost() registered
mailserver    | [[  INF  ]]  _setup_postfix_dhparam() registered
mailserver    | [[  INF  ]]  _setup_postfix_postscreen() registered
mailserver    | [[  INF  ]]  _setup_postfix_sizelimits() registered
mailserver    | [[  INF  ]]  _setup_postfix_access_control() registered
mailserver    | [[  INF  ]]  _setup_postfix_relay_hosts() registered
mailserver    | [[  INF  ]]  _setup_postfix_override_configuration() registered
mailserver    | [[  INF  ]]  _setup_logrotate() registered
mailserver    | [[  INF  ]]  _setup_mail_summary() registered
mailserver    | [[  INF  ]]  _setup_logwatch() registered
mailserver    | [[  INF  ]]  _setup_user_patches() registered
mailserver    | [[  INF  ]]  _setup_chksum_file() registered
mailserver    | [[  INF  ]]  _fix_var_mail_permissions() registered
mailserver    | [[  INF  ]]  _fix_var_amavis_permissions() registered
mailserver    | [[  INF  ]]  _fix_cleanup_clamav() registered
mailserver    | [[  INF  ]]  _fix_cleanup_spamassassin() registered
mailserver    | [[  INF  ]]  _misc_save_states() registered
mailserver    | [[  INF  ]]  _start_daemons_cron() registered
mailserver    | [[  INF  ]]  _start_daemons_rsyslog() registered
mailserver    | [[  INF  ]]  _start_daemons_dovecot() registered
mailserver    | [[  INF  ]]  _start_daemons_update_check() registered
mailserver    | [[  INF  ]]  _start_daemons_opendkim() registered
mailserver    | [[  INF  ]]  _start_daemons_opendmarc() registered
mailserver    | [[  INF  ]]  _start_daemons_postfix() registered
mailserver    | [[  INF  ]]  _start_changedetector() registered
mailserver    | [[  INF  ]]  _start_daemons_amavis() registered
mailserver    | [ TASKLOG ]  Checking configuration
mailserver    | [[ TASKS ]]  Checking that hostname/domainname is provided or overridden
mailserver    | [[  INF  ]]  Domain has been set to yuzhongit.com
mailserver    | [[  INF  ]]  Hostname has been set to mail.yuzhongit.com
mailserver    | [ TASKLOG ]  Configuring mail server
mailserver    | [[ TASKS ]]  Setting up default variables
mailserver    | [[ TASKS ]]  Setting file/folder permissions
mailserver    | [[ TASKS ]]  Setting up Dovecot
mailserver    | [[  INF  ]]  Dovecot maildir format configured (default)
mailserver    | [[  INF  ]]  Spam messages will be moved to the Junk folder.
mailserver    | [[ TASKS ]]  Setting up dovecot dhparam
mailserver    | [[  INF  ]]  dovecot will use official standardized DH parameters (ffdhe4096).
mailserver    | [[ TASKS ]]  Setting up Dovecot quota
mailserver    | [[ TASKS ]]  Setting up Dovecot Local User
mailserver    | [[  INF  ]]  '/tmp/docker-mailserver/postfix-accounts.cf' is not provided. No mail account created.
mailserver    | [  FATAL  ]  Unless using LDAP, you need at least 1 email account to start Dovecot.
mailserver    | [  ERROR  ]  Shutting down..
mailserver    | [[ TASKS ]]  Disabling postfix DNS block list (zen.spamhaus.org)
mailserver    | [[ TASKS ]]  Disabling postscreen DNS block lists
mailserver    | 2022-04-01 17:48:36,248 WARN received SIGTERM indicating exit request
mailserver    | [[ TASKS ]]  Setting up DKIM
mailserver    | [ WARNING ]  No DKIM key provided. Check the documentation on how to get your keys.
mailserver    | [[  INF  ]]  Nameservers added to /etc/opendkim.conf
mailserver    | [[ TASKS ]]  Setting up SSL
mailserver    | [[  INF  ]]  TLS configured with 'modern' ciphers
mailserver    | [[  INF  ]]  Configuring certificates using key /tmp/ssl/mail.yuzhongit.com_key.key and cert /tmp/ssl/mail.yuzhongit.com_chain.crt
mailserver    | [[  INF  ]]  SSL configured with 'Manual' certificates
mailserver    | [[ TASKS ]]  Setting up PERMIT_DOCKER Option
mailserver    | [[  INF  ]]  Adding docker network in my networks
mailserver    | [[ TASKS ]]  Setting up mailname / creating /etc/mailname
mailserver    | [[ TASKS ]]  Setting up Amavis
mailserver    | [ TASKLOG ]  Welcome to docker-mailserver 10.5.0
mailserver    | [ TASKLOG ]  Initializing setup
mailserver    | [[ TASKS ]]  Registering functions
mailserver    | [[  INF  ]]  _check_hostname() registered
mailserver    | [[  INF  ]]  _setup_supervisor() registered
mailserver    | [[  INF  ]]  _setup_default_vars() registered
mailserver    | [[  INF  ]]  _setup_file_permissions() registered
mailserver    | [[  INF  ]]  _setup_dovecot() registered
mailserver    | [[  INF  ]]  _setup_dovecot_dhparam() registered
mailserver    | [[  INF  ]]  _setup_dovecot_quota() registered
mailserver    | [[  INF  ]]  _setup_dovecot_local_user() registered
mailserver    | [[  INF  ]]  _setup_dnsbl_disable() registered
mailserver    | [[  INF  ]]  _setup_dkim() registered
mailserver    | [[  INF  ]]  _setup_ssl() registered
mailserver    | [[  INF  ]]  _setup_docker_permit() registered
mailserver    | [[  INF  ]]  _setup_mailname() registered
mailserver    | [[  INF  ]]  _setup_amavis() registered
mailserver    | [[  INF  ]]  _setup_dmarc_hostname() registered
mailserver    | [[  INF  ]]  _setup_postfix_hostname() registered
mailserver    | [[  INF  ]]  _setup_dovecot_hostname() registered
mailserver    | [[  INF  ]]  _setup_postfix_smtputf8() registered
mailserver    | [[  INF  ]]  _setup_postfix_sasl() registered
mailserver    | [[  INF  ]]  _setup_postfix_sasl_password() registered
mailserver    | [[  INF  ]]  _setup_security_stack() registered
mailserver    | [[  INF  ]]  _setup_postfix_aliases() registered
mailserver    | [[  INF  ]]  _setup_postfix_vhost() registered
mailserver    | [[  INF  ]]  _setup_postfix_dhparam() registered
mailserver    | [[  INF  ]]  _setup_postfix_postscreen() registered
mailserver    | [[  INF  ]]  _setup_postfix_sizelimits() registered
mailserver    | [[  INF  ]]  _setup_postfix_access_control() registered
mailserver    | [[  INF  ]]  _setup_postfix_relay_hosts() registered
mailserver    | [[  INF  ]]  _setup_postfix_override_configuration() registered
mailserver    | [[  INF  ]]  _setup_logrotate() registered
mailserver    | [[  INF  ]]  _setup_mail_summary() registered
mailserver    | [[  INF  ]]  _setup_logwatch() registered
mailserver    | [[  INF  ]]  _setup_user_patches() registered
mailserver    | [[  INF  ]]  _setup_chksum_file() registered
mailserver    | [[  INF  ]]  _fix_var_mail_permissions() registered
mailserver    | [[  INF  ]]  _fix_var_amavis_permissions() registered
mailserver    | [[  INF  ]]  _fix_cleanup_clamav() registered
mailserver    | [[  INF  ]]  _fix_cleanup_spamassassin() registered
mailserver    | [[  INF  ]]  _misc_save_states() registered
mailserver    | [[  INF  ]]  _start_daemons_cron() registered
mailserver    | [[  INF  ]]  _start_daemons_rsyslog() registered
mailserver    | [[  INF  ]]  _start_daemons_dovecot() registered
mailserver    | [[  INF  ]]  _start_daemons_update_check() registered
mailserver    | [[  INF  ]]  _start_daemons_opendkim() registered
mailserver    | [[  INF  ]]  _start_daemons_opendmarc() registered
mailserver    | [[  INF  ]]  _start_daemons_postfix() registered
mailserver    | [[  INF  ]]  _start_changedetector() registered
mailserver    | [[  INF  ]]  _start_daemons_amavis() registered
mailserver    | [ TASKLOG ]  Checking configuration
mailserver    | [[ TASKS ]]  Checking that hostname/domainname is provided or overridden
mailserver    | [[  INF  ]]  Domain has been set to yuzhongit.com
mailserver    | [[  INF  ]]  Hostname has been set to mail.yuzhongit.com
mailserver    | [ TASKLOG ]  Configuring mail server
mailserver    | [[ TASKS ]]  Setting up default variables
mailserver    | [[ TASKS ]]  Setting file/folder permissions
mailserver    | [[ TASKS ]]  Setting up Dovecot
mailserver    | [[  INF  ]]  Dovecot maildir format configured (default)
mailserver    | [[  INF  ]]  Spam messages will be moved to the Junk folder.
mailserver    | [[ TASKS ]]  Setting up dovecot dhparam
mailserver    | [[  INF  ]]  dovecot will use official standardized DH parameters (ffdhe4096).
mailserver    | [[ TASKS ]]  Setting up Dovecot quota
mailserver    | [[ TASKS ]]  Setting up Dovecot Local User
mailserver    | [[  INF  ]]  '/tmp/docker-mailserver/postfix-accounts.cf' is not provided. No mail account created.
mailserver    | [  FATAL  ]  Unless using LDAP, you need at least 1 email account to start Dovecot.
mailserver    | [  ERROR  ]  Shutting down..
mailserver    | [[ TASKS ]]  Disabling postfix DNS block list (zen.spamhaus.org)
mailserver    | Error: sed -i /^smtpd_recipient_restrictions = / s/, reject_rbl_client zen.spamhaus.org// /etc/postfix/main.cf
mailserver    | 2022-04-01 17:48:46,744 WARN received SIGTERM indicating exit request
mailserver    | [[ TASKS ]]  Disabling postscreen DNS block lists
mailserver    | [[ TASKS ]]  Setting up DKIM
mailserver    | [ WARNING ]  No DKIM key provided. Check the documentation on how to get your keys.
mailserver    | Nameservers 127.0.0.11
mailserver    | [[ TASKS ]]  Setting up SSL
mailserver    | [[  INF  ]]  TLS configured with 'modern' ciphers
mailserver    | [[  INF  ]]  Configuring certificates using key /tmp/ssl/mail.yuzhongit.com_key.key and cert /tmp/ssl/mail.yuzhongit.com_chain.crt
mailserver    | Error: sed -i -r s|^(smtpd_tls_chain_files =).*|\1 /etc/dms/tls/key /etc/dms/tls/cert| /etc/postfix/main.cf
mailserver    | Error: sed -i -r -e s|^(ssl_key =).*|\1 </etc/dms/tls/key| -e s|^(ssl_cert =).*|\1 </etc/dms/tls/cert| /etc/dovecot/conf.d/10-ssl.conf
mailserver    | [[  INF  ]]  SSL configured with 'Manual' certificates
mailserver    | [[ TASKS ]]  Setting up PERMIT_DOCKER Option
mailserver    | [[  INF  ]]  Adding docker network in my networks
mailserver    | [[ TASKS ]]  Setting up mailname / creating /etc/mailname
mailserver    | [[ TASKS ]]  Setting up Amavis
[root@host-10-0-0-107 mailserver]#
```

**Comment by georglauterbach** [comment] 2022-04-01 10:34
From the logs I see that you did not follow the setup guide thoroughly. This issue tracker is **not** for personal support!

You have not setup an email. Therefore, the server restarts - again and again. The README explains all you need! Make sure to read the README and the documentation **before** opening an issue!

**Comment by georglauterbach** [comment] 2022-04-01 10:36
This issue is not a bug. I'm sorry to inform you about this, but I am closing and locking this ticket because the issue tracker is not supposed to be used for personal support [see contribution guidelinee].

**Closed by georglauterbach** 2022-04-01 10:36 UTC
Labels: meta/needs triage, meta/help wanted, kind/question, priority/low

**Comment by jasonbohan** [comment] 2022-04-02 07:28
Thanks ,I fixed it. Now it running.
