### ISSUE TITLE
other: Cannot build Dockerfile

### ISSUE THREAD

**Issue by di-rect** [docker-mailserver/docker-mailserver#3277] opened 2023-04-20 06:52 UTC
### Subject

Other

### Description

I cannot build the image with the provided Dockerfile:

```
Sending build context to Docker daemon  430.6kB
Error response from daemon: dockerfile parse error line 24: unknown instruction: CHMOD
```

What can cause this "small" bug ?

**Comment by georglauterbach** [comment] 2023-04-20 07:46
This should definitely have been a bug report. Because you did not use this template, I'm marking your issue as `issue/no template - no support`.


---

You're not providing any information about your setup. What do you think how we should help you now? We can only guess: either you're not using `make build`, or your Docker version is not new enough - in both cases, you probably did not [read our documentation (on building the image)](https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/docker-build/), which makes such issues even more annoying.

**Comment by georglauterbach** [comment] 2023-04-20 07:51
Closing this; reason: violation of community rules | issue does not comply with [the standards layed out for opening issues](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#opening-an-issue)).

**Closed by georglauterbach** 2023-04-20 07:51 UTC
Labels: issue/no template - no support, issue/(likely) user-related misconfiguration

**Comment by di-rect** [comment] 2023-04-20 07:52
This is strange, I can make a bugreport, but you mostly do that AFTER you know why things are happening. Most of the time Bugreports are support questions, so that is why I start here. 

You are going too fast.

**Comment by polarathene** [comment] 2023-04-21 00:18
> https://github.com/docker-mailserver/docker-mailserver/blob/2b330fdc493d983f54a8f8868393d496e1e5a611/Dockerfile#L23-L24

This is where your error happens, it is very likely because you are not using Docker with BuildKit enabled. This feature (HereDoc) has [been available since around July 2021](https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/).

---

@georglauterbach is handling this correctly, although you may not have been aware of the docs for this, he did link you to it. It makes it very clear that we use [BuildKit features that need a modern release of Docker Engine](https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/docker-build/#environment), and how to get an updated version of Docker from official Docker docs.

As our docs linked also explain, if you don't use the `make build` command, then for Docker releases prior to 2023, you'll need to add the `DOCKER_BUILDKIT=1` ENV before running the `docker build` command.

---

I understand that the response you got may have been a bit strict and unwelcoming, and I understand that our bug report form is very thorough, but the least you could have done if skipping it was provide more context such as what version of docker you used and how you try to build the `Dockerfile`.

Additionally you were provided a response with information that guessed what the cause was and how you could resolve it. You did not acknowledge if you read that and if it solved your issue.
