### ISSUE TITLE
bug report: 

### ISSUE THREAD

**Issue by kristvanbesien** [docker-mailserver/docker-mailserver#4133] opened 2024-07-25 12:38 UTC
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I have setup a forward-only mail server (so no local mail delivery) and am getting the following error in mail.log every minute:

```
2024-07-25T14:24:43.834693+02:00 cookiemonster postfix/master[675]: warning: process /usr/lib/postfix/sbin/virtual pid 124967 exit status 1
2024-07-25T14:24:43.834725+02:00 cookiemonster postfix/master[675]: warning: /usr/lib/postfix/sbin/virtual: bad command startup -- throttling
2024-07-25T14:25:43.901108+02:00 cookiemonster postfix/virtual[125064]: fatal: bad string length 0 < 1: virtual_mailbox_base =
```

The mail server works fine otherwise. Incoming mail is accepted (and forwarded per the configured aliase) and outgoing mail is send out.

### 👟 Reproduction Steps

This is the environment file I used to start the containers with:

```
# Relay only server

PERMIT_DOCKER=host
ENABLE_POP3=
ENABLE_CLAMAV=0
SMTP_ONLY=1
ENABLE_SPAMASSASSIN=0
ENABLE_FETCHMAIL=0

LOG_LEVEL=debug

SUPERVISOR_LOGLEVEL=debug

POSTMASTER_ADDRESS=postmaster@kri.st

ENABLE_UPDATE_CHECK=1

# Customize the update check interval.
# Number + Suffix. Suffix must be 's' for seconds, 'm' for minutes, 'h' for hours or 'd' for days.
UPDATE_CHECK_INTERVAL=1d

NETWORK_INTERFACE=tap0

SSL_TYPE=manual
SSL_CERT_PATH=/tmp/tls/certs/cookiemonster.crt
SSL_KEY_PATH=/tmp/tls/private/cookiemonster.key
```

My suspicion is that the variable virtual_mailbox_base somwhow is not correctly set.

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Fedora 40

### ⚙️ Container configuration files

```yml
I am actually using podman and creating the container with ansible. The syntax however follows closely the compose syntax, and I doubt that this is the source of the issue.
```

**Comment by kristvanbesien** [comment] 2024-07-27 08:50
If this is a user misconfiguration, what env variable do I need to add so that this error goes away? I based my env file on the  the FAQ, which gives an example of a relay only server.

**Comment by polarathene** [comment] 2024-07-27 10:30
**Heads-up:**

This response is presently incomplete and needs some edits done as I had some mistakes while putting it together. I plan to revisit in about 12 hours or so. Since you've added a new comment though, perhaps it'll give you the information you need to resolve this for you.

I'll revise this later with proper updates to config and technical details.

**Summary:**
You have aliases configured, those populate `/etc/postfix/vhost` which then triggers the `virtual_mailbox_base` warning, but if you fix that you'd possibly still run into another about uid/gid settings (at least for local delivery). Postfix is recognizing the aliases as managed domains but they're being relayed remotely, yet that's being done via the `virtual` delivery agent, etc as covered below.

Two outcomes from adjusting config is the warning goes away and:
- a bounce mail is sent after accepting the mail, stating that the account mailbox doesn't exist locally to deliver to, or if it was configured to the mail is stored locally (_without Dovecot_).
- alternatively if DNS lookup fails, that there is no host to relay/forward that mail to.

---

## WIP response

```bash
# By default should be configured:
$ grep virtual_mailbox_base /etc/postfix/main.cf

# Ask postfix what the current configured value is:
$ postconf virtual_mailbox_base
virtual_mailbox_base =
```

The `virtual` delivery agent shouldn't matter in this setup due to `SMTP_ONLY=1`, as you can see by the docs for [`virtual_mailbox_base`](https://www.postfix.org/postconf.5.html#virtual_mailbox_base), it's used for prepending a path for mail delivery.

DMS uses Dovecot over LMTP for virtual delivery transport, which delegates Dovecot to manage storage for that. As you used `SMTP_ONLY=1` you chose not to enable Dovecot.

Here is the actual minimum reproduction required:

```yaml
services:
  dms:
    image: mailserver/docker-mailserver:14.0
    hostname: mail.example.test
    environment:
      # No Dovecot (thus no users to authenticate with, or inboxes to deliver to)
      SMTP_ONLY: 1
      # WORKAROUND: Avoid authentication by allowing mail to be sent without credentials via port 25 from trusted IPs
      PERMIT_DOCKER: container
```

```console
$ docker compose up -d

# Send test mail from the container to the container:
$ docker compose exec dms swaks --helo not-relevant.test --server mail.example.test --port 25 --from hello@not-relevant.test --to user@example.test

# Logs from report:
$ docker compose logs dms | grep virtual
dms  | 2024-07-25T21:31:27.895425+00:00 mail postfix/virtual[595]: fatal: bad string length 0 < 1: virtual_mailbox_base =
dms  | 2024-07-25T21:31:28.896193+00:00 mail postfix/master[504]: warning: process /usr/lib/postfix/sbin/virtual pid 595 exit status 1
dms  | 2024-07-25T21:31:28.896231+00:00 mail postfix/master[504]: warning: /usr/lib/postfix/sbin/virtual: bad command startup -- throttling
```

---

For further clarification of the problem, here is two DMS containers, the one above, and another one with Dovecot and users provisioned to deliver to:

```yaml
services:
  # We'll send mail from this container via swaks:
  dms-sender:
    image: mailserver/docker-mailserver:14.0
    hostname: mail.example-sender.test
    environment:
      SMTP_ONLY: 1
      # Adjusted to support mail clients from outside the container too (from dms-receiver):
      PERMIT_DOCKER: connected-networks

  # This DMS container will receive mail that we send from swaks
  dms-receiver:
      image: mailserver/docker-mailserver:14.0
      hostname: mail.example-receiver.test
      environment:
        # Trust connections from an IP belonging to networks available to this container
        # This bypasses some security checks such as DNS:
        PERMIT_DOCKER: connected-networks
      # Pre-provisioned accounts config:
      configs:
        - source: dms-accounts
          target: /tmp/docker-mailserver/postfix-accounts.cf

# NOTE: This feature requires Docker Compose v2.23.1 (Nov 2023) or newer:
configs:
  # DMS expects an account to be configured to run, this config provides one
  # You can add new accounts with `docker compose exec dms setup email add user@example.test bad-password`
  # Login credentials:
  # user: "john.doe@example.test" password: "secret"
  # user: "jane.doe@example.test" password: "secret"
  dms-accounts:
    # NOTE: `$` needed to be repeated to escape it,
    # which opts out of the `compose.yaml` variable interpolation feature.
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
      jane.doe@example.test|{SHA512-CRYPT}$$6$$o65y1ZXC4ooOPLwZ$$7TF1nYowEtNJpH6BwJBgdj2pPAxaCvhIKQA6ww5zdHm/AA7aemY9eoHC91DOgYNaKj1HLxSeWNDdvrp6mbtUY.
```

```bash
docker compose up -d
docker compose exec dms-sender swaks --helo not-relevant.test --server mail.example-receiver.test --port 25 --from hello@not-relevant.test --to john.doe@example.test

# No output, dms-receiver accepted the mail for a valid user and stored it:
docker compose logs | grep virtual

# Now send mail the other way, dms-receiver to dms-sender:
docker compose exec dms-receiver swaks --helo not-relevant.test --server mail.example-sender.test --port 25 --from hello@not-relevant.test --to john.doe@example.test

# Now the same error as the original reproduction,
# as expected since `SMTP_ONLY=1` does not support receiving mail:
$ docker compose logs | grep virtual
dms-sender | 2024-07-25T22:10:46.323211+00:00 mail postfix/virtual[589]: fatal: bad string length 0 < 1: virtual_mailbox_base =
dms-sender | 2024-07-25T22:10:47.324829+00:00 mail postfix/master[521]: warning: process /usr/lib/postfix/sbin/virtual pid 589 exit status 1
dms-sender | 2024-07-25T22:10:47.324891+00:00 mail postfix/master[521]: warning: /usr/lib/postfix/sbin/virtual: bad command startup -- throttling
```

Let's look into other `virtual_` settings Postfix might have configured:

```console
$ docker compose exec dms-sender bash
$ grep virtual /etc/postfix/main.cf
virtual_mailbox_domains = /etc/postfix/vhost
virtual_alias_maps = texthash:/etc/postfix/virtual
virtual_mailbox_limit = 0

# Referenced files are empty:

# This file would be populated with alias mappings if `postfix-virtual.cf` exists:
$ cat /etc/postfix/virtual

# This file would be populated from mail domains if `postfix-accounts.cf` or `postfix-virtual.cf` exists:
$ cat /etc/postfix/vhost
```

[`virtual_alias_maps`](https://www.postfix.org/postconf.5.html#virtual_alias_maps) and [`virtual_mailbox_domains`](https://www.postfix.org/postconf.5.html#virtual_mailbox_domains) are both paths we configured by default for DMS in our `main.cf` (_The related scripts during container startup create an empty file for each_):

https://github.com/docker-mailserver/docker-mailserver/blob/32c0a346fcec975ba133443d98e3a1e7c0d78714/target/postfix/main.cf#L102-L106

If we also compare that to `dms-receiver` which is configured for Dovecot, we'll see two other related results in `/etc/postfix/main.cf` which configure:

```
virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
virtual_transport = lmtp:unix:/var/run/dovecot/lmtp
```

[`virtual_transport`](https://www.postfix.org/postconf.5.html#virtual_transport) defaults to `virtual`, which would be the `virtual` service defined in `/etc/postfix/master.cf` I think? (_unix socket service, that delegates delivery the `virtual` delivery agent executable_):

https://github.com/docker-mailserver/docker-mailserver/blob/32c0a346fcec975ba133443d98e3a1e7c0d78714/target/postfix/master.cf#L73

You'll get other failures if you try to unset `virtual_transport` by assigning it a blank value (_to avoid the default `virtual`_).

Instead you can do either of these (_both seem to have the same effect of rejecting delivery, sending a bounce mail_):

```
# Unset this:
virtual_mailbox_domains=

# Or provide a default base path:
virtual_mailbox_base=/var/mail
```

---

## Reference - Local delivery (`local-part@${HOSTNAME}`)

This doesn't affect the issue, but worth noting that currently with DMS and `SMTP_ONLY=1` some incoming mail may still be delivered, along with sent and delivered internally. Anything sent to `root` will by default forward to the postmaster address, ensure that's configured correctly.

The `local-part` is used to perform a lookup to system users (_such as `root`, `amavis`, or other services assigned a user_) to perform local delivery to `/var/mail`. Local delivery with Postfix is via the `local` delivery agent.

This is when the Postfix `main.cf` setting `mydestination` matches the `domain-part` of the recipient address for incoming mail. If there is a match it'll accept the mail to deliver it to `/var/mail` (_unrelated to Dovecot storage which also delivers into `/var/mail` for virtual mailboxes and virtual aliases_).

```console
$ cat /etc/passwd

root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
_apt:x:42:65534::/nonexistent:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
clamav:x:200:200::/var/lib/clamav:/usr/sbin/nologin
postfix:x:100:102::/var/spool/postfix:/usr/sbin/nologin
fetchmail:x:101:65534::/var/lib/fetchmail:/bin/false
postsrsd:x:102:105::/var/lib/postsrsd:/usr/sbin/nologin
opendkim:x:103:106::/run/opendkim:/usr/sbin/nologin
opendmarc:x:104:107::/run/opendmarc:/usr/sbin/nologin
policyd-spf:x:105:108::/nonexistent:/usr/sbin/nologin
_mta-sts:x:106:109::/var/lib/mta-sts/:/usr/sbin/nologin
postgrey:x:107:110::/var/lib/postgrey:/usr/sbin/nologin
amavis:x:999:999:AMaViS system user:/var/lib/amavis:/bin/sh
debian-spamd:x:108:111::/var/lib/spamassassin:/usr/sbin/nologin
dovecot:x:109:112:Dovecot mail server,,,:/usr/lib/dovecot:/usr/sbin/nologin
dovenull:x:110:113:Dovecot login user,,,:/nonexistent:/usr/sbin/nologin
_rspamd:x:111:114:rspamd spam filtering system,,,:/var/lib/rspamd:/usr/sbin/nologin
redis:x:112:115::/var/lib/redis:/usr/sbin/nologin
syslog:x:113:65534::/nonexistent:/usr/sbin/nologin
docker:x:5000:5000::/home/docker:/bin/bash
```

Additionally we have local aliases (_only has manual config support via `postfix-aliases.cf`, no integration with `setup` CLI_).

This presently configures `root` mail to be aliased to the `postmaster` address which also has a default that assumes DMS will manage mail for `@example.test` addresses when the hostname is `anything.example.test`. Note this postmaster assumption is for any `hostname` configured that has more than two DNS labels, it'll trim the left-most label. It's a legacy issue that still hasn't been addressed, but you won't be affected if you explicitly configure the postmaster ENV.

```console
$ cat /etc/aliases

root: postmaster@example.test
```

Postfix will also send mail out from some of it's own internal `local-part` users, and append the `myorigin` to complete the sender address IIRC.

**Comment by polarathene** [comment] 2024-07-31 04:25
Sorry for delay, investigation completed 🎉 

## Problem summary

For your issue I have determined the following:
- No, `virtual_mailbox_base=/var/mail` will not help you, that is misdirection. You do not want Postfix accepting mail to store in the DMS container, otherwise you'd not use `SMTP_ONLY=1` and just use Dovecot (_or the Postfix equivalent shown above_).
- You want to use our **`postfix-main.cf` config override feature** with `virtual_mailbox_domains=`. This is technically a bug that DMS can fix as the default points to `/etc/postfix/vhost` which contains a list of domains found in `postfix-accounts.cf` and `postfix-virtual.cf`.
  - This setting tells Postfix that these are mail domains with virtual mailboxes that Postfix should deliver to internally (_only if your virtual alias did not resolve to an external mail address, or the mail was for a recipient at that domain but has no matching alias or account, thus an invalid recipient to alias for_).
  - By ignoring this domain list, Postfix will instead relay the mail outbound after resolving DNS. If the client delivering mail to DMS/Postfix on port 25 is not within the `PERMIT_DOCKER` network range, this will be forbidden with the error `Relay access denied`, even though you have an alias for the domain configured Postfix will enforce an authentication/trust requirement to relay.
  - A related setting `virtual_alias_domains` can instead refer to the managed domain list of `/etc/postfix/vhost`. That will allow mail arriving on port 25 from untrusted clients to be relayed when there is a matching alias entry (_`virtual_alias_maps = /etc/postfix/virtual`, aka `postfix-virtual.cf`_).

## Solution

In your [Config Volume](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/advanced/optional-config/#volumes), add the [`postfix-main.cf` override file](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/advanced/override-defaults/postfix/) with contents:

```
virtual_mailbox_domains=
virtual_alias_domains=/etc/postfix/vhost
```

## Detailed reproduction example (with fix applied)

This example demonstrates the full flow with a few alias configurations you can test.

Just copy/paste the `compose.yaml` below and run that with `docker compose up --force-recreate` and try the commands shown in the `CLI USAGE` comment below for `send-test-mail` 👍 

If you comment out the `dms-main` config for `dms-forwarding-mta` service, you should be able to reproduce the `fatal` error log line you reported.

```yaml
services:
  # This container represents your DMS deployment already in production.
  # No DMS accounts or mailbox storage, only forwarding mail via alias mappings.
  dms-forwarding-mta:
    image: mailserver/docker-mailserver:14.0
    hostname: mail.example.test
    environment:
      SMTP_ONLY: 1
    # WORKAROUND: Without proper DNS setup, this is needed to resolve
    # the recipient mail domain IP to the `dms-destination-mta` container.
    links:
      - "dms-destination-mta:destination.test"
    # Use `volumes` instead to provide your configs if you need to persist changes,
    # Otherwise you can avoid separate files via the Docker Compose `configs` feature:
    configs:
      - source: dms-aliases
        target: /tmp/docker-mailserver/postfix-virtual.cf
      # WORKAROUND: This is presently needed to avoid the bug you're encountering:
      - source: dms-main
        target: /tmp/docker-mailserver/postfix-main.cf

  # This container represents the external mail server that our example recipient belongs to.
  # `dms-forwarding-mta` will receive mail at it's alias and forward delivery via relay to this MTA.
  dms-destination-mta:
      image: mailserver/docker-mailserver:14.0
      hostname: mail.destination.test
      environment:
        # WORKAROUND: Trust connections from an IP belonging to networks available to this container.
        # This bypasses some security checks such as DNS. Without it the sender address `hello@alpine.test` will be rejected.
        PERMIT_DOCKER: connected-networks
      # Pre-provisioned accounts config:
      configs:
        - source: dms-accounts
          target: /tmp/docker-mailserver/postfix-accounts.cf

  # OPTIONAL: Allows you to send a test mail quickly. You can try with your own mail client instead too.
  # CLI USAGE:
  # - Default recipient address (`valid@example.test`): `docker compose --profile testing run --rm send-test-mail`
  # - Override default by adding a custom command to the end (appends to entrypoint command):
  #    - DMS accepts mail but will fail, sends a bounce mail: `docker compose --profile testing run --rm send-test-mail --to bounce@example.test`
  #    - DMS has no matching alias, rejects mail early: `docker compose --profile testing run --rm send-test-mail --to reject@example.test`
  send-test-mail:
    # This container will only be used with `docker compose run` command and exit afterwards.
    # The `profiles` setting here prevents it from being started by default with other services during `docker compose up`.
    profiles:
      - testing
    # Prepare an image with the `swaks` package installed. We declare an inline `Dockerfile` and use HereDoc syntax for a single easy to read `RUN` layer:
    # (Alternatively just use DMS as the image like other services in this example, since DMS already has `swaks` installed.
    build:
      # YAML syntax `|`, this allows multi-line string values that preserves line-breaks:
      # (`Dockerfile` multi-line `RUN` directive must end lines with `LF`, copy/paste on Windows may switch to `CRLF` causing build failures):
      dockerfile_inline: |
        FROM alpine:edge
        # Add `swaks` from the edge testing repo, as Alpine has not promoted the package to edge or a tagged release yet:
        # (also requires installing `perl-net-ssleay` which is an implicit dependency)
        RUN <<EOF
          apk add swaks --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing
          apk add perl-net-ssleay
        EOF
    # YAML syntax `>`, this folds the multi-line yaml content to single line value:
    # (Here we are providing the common portion of the `swaks` command to run)
    entrypoint: >
      swaks
        --server mail.example.test
        --port 25
        --from hello@alpine.test
    # The default `command` that is appended to the `entrypoint` value:
    # (It can be overriden by the `docker compose run` command)
    command: --to valid@example.test
    # The `hostname` will resolve in the network when DMS does a lookup (via the embedded DNS of Docker):
    # - Prevents: `450 4.1.8 <hello@alpine.test>: Sender address rejected: Domain not found`,
    #   except for the next hop (relay) to `dms-receiver` which will still raise this error without `PERMIT_DOCKER` set.
    # - Also used by `swaks` as the default client EHLO (`--helo` / `--ehlo`),
    #   which must be an FQDN for a basic SPF check to pass.
    hostname: alpine.test

# Using the Docker Compose `configs.content` feature instead of volume mounting separate files.
# NOTE: This feature requires Docker Compose v2.23.1 (Nov 2023) or newer:
# https://github.com/compose-spec/compose-spec/pull/446
configs:
  # Virtual alias config. Postfix docs for syntax rules: https://www.postfix.org/virtual.5.html
  # - Only the `valid@example.test` alias and `@catch-all.test` wildcard alias will forward to a `@destination.test` address.
  # - If the alias resolves to a recipient that is not valid, the mail client will be rejected.
  # - Wildcard aliases will always be considered valid at this point, sending bounce mail instead of an early failure.
  dms-aliases:
    content: |
      # Resolves to external MTA, mail is forwarded (relayed) to that MTA:
      valid@example.test jane.doe@destination.test

      # DMS manages `@example.test` and `john.doe@example.test` is not a valid alias or mailbox, mail is accepted but bounced:
      bounce@example.test invalid@example.test
      invalid@example.test john.doe@example.test

      # Any mail for recipients of `@wildcard.test` will be aliased to `@example.test`:
      # - `dms-forwarding-mta` will accept mail for any recipient of this wildcard. The mail client always considers it successful as a result.
      # - `dms-destination-mta` may reject if the recipient is not valid, sending a bounce mail to the sender address.
      @wildcard.test @example.test

      # Any mail for recipients of `@catch-all.test` will be forwarded to `john.doe@destination.test`:
      @catch-all.test john.doe@destination.test

  # WORKAROUND:
  # With `SMTP_ONLY=1` you do not want to associate any managed domains to mailboxes. DMS is only forwarding mail for virtual aliases.
  # - `virtual_mailbox_domains` thus must be set to empty.
  # - `virtual_alias_domains` needs to know about these domains instead.
  # - The two settings must not share the same domains, just like they must be distinct from `mydestination` which the `local` delivery agent handles.
  dms-main:
    content: |
      virtual_mailbox_domains=
      virtual_alias_domains=/etc/postfix/vhost

  # Mailbox addresses for `dms-destination-mta` to accept delivery into:
  dms-accounts:
    # NOTE: `$` needed to be repeated to escape it which opts out of the `compose.yaml` variable interpolation feature. The hashed password is `secret`.
    content: |
      john.doe@destination.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
      jane.doe@destination.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```

Please note that as per my findings, you may have mail arriving to DMS without a valid alias match, or misconfigured virtual aliases that trigger the actual problem you've reported.

The solution will either reject the mail from the client early, or trigger a bounce mail.

Additionally, your usage of `PERMIT_DOCKER` with port 25 instead of configuring such trusted clients to submit mail via port 587/465 with credentials is another area to consider. DMS presently doesn't offer an alternative account provisioner for `SMTP_ONLY=1`, but you can find guidance from the community on manually doing so, or just use Dovecot and don't expose port 25 publicly which should avoid all these concerns 😅

**Comment by polarathene** [comment] 2024-07-31 04:36
> If this is a user misconfiguration, what env variable do I need to add so that this error goes away?

Remove the `SMTP_ONLY=1` ENV should do the trick? This disabled Dovecot, but if you don't have any major reason to do so, just stay with our default with Dovecot enabled and don't publish port 25 publicly.

---

> I based my env file on the the FAQ, which gives an example of a relay only server.

You are mistaken? There is not a single mention of "relay" in the [FAQ](https://docker-mailserver.github.io/docker-mailserver/v14.0/faq/)?

There is a [FAQ entry regarding `SMTP_ONLY=1`](https://docker-mailserver.github.io/docker-mailserver/v14.0/faq/#how-can-i-authenticate-users-with-smtp_only1) and adding back authentication support.

`SMTP_ONLY=1` also exists in a [community contributed guide for using DMS to forward mail it receives via aliases](https://docker-mailserver.github.io/docker-mailserver/v14.0/examples/use-cases/forward-only-mailserver-with-ldap-authentication/#building-a-forward-only-mail-server). Perhaps you were recalling that page? The initial group of ENV you shared matches that, so that seems to be the case.

I consider this issue resolved. You may chime in with any feedback, but I may lack the time to proceed any further with this.

**Closed by polarathene** 2024-07-31 04:36 UTC
Labels: service/postfix, issue/(likely) user-related misconfiguration, kind/bug/report
