### ISSUE TITLE
Enable ONE_DIR on existing installation

### ISSUE THREAD

**Issue by rhyst** [docker-mailserver/docker-mailserver#2770] opened 2022-09-12 17:37 UTC
# Subject

Other

## Description

Is it possible to enable the ONE_DIR option after running the server for a while? i.e. I have an account and mail etc. already set up. What would happen if I enable ONE_DIR now?

**Comment by georglauterbach** [comment] 2022-09-13 06:43
Without `ONE_DIR`, data is a bit scattered. Enabling it would probably result in data not being shown. How do you currently persist your data? `ONE_DIR` was intended to provide a single directory to mount your volumes to, to have persistence.

Looking at the code: https://github.com/docker-mailserver/docker-mailserver/blob/f8e1bb0f42049789e9700778552166a47cac783c/target/scripts/startup/misc-stack.sh#L14-L83

your data should not be removed (at least by our code, I don't know what a container restart does).

**Comment by rhyst** [comment] 2022-09-14 10:43
Currently I just mount the other volumes:

```
      - "{{ service_root }}/mail/mail/:/var/mail/"
      - "{{ service_root }}/mail/mail-logs/:/var/log/mail/"
      - "{{ service_root }}/mail/config/:/tmp/docker-mailserver/"
```

And this seems to work fine. 

It was not clear to me what the difference or advantage was with ONE_DIR but it did seem as though the files were a bit "tidier" (I tried it with a new container).

I was wondering if things would be "migrated" if I enabled it, but it sounds like it would not 😄

**Comment by georglauterbach** [comment] 2022-09-14 11:57
With your setup, you'd loose everything under `/var/lib/` for example, including some of the data Postfix or Dovecot saves. Mails would not get lost though, as they are located under `/var/mail/`.

**Comment by rhyst** [comment] 2022-09-14 12:13
Ah, I was not aware there was additional state. 

My '/var/mail-state'  dir is empty so it seems like I would hit the second of the conditional blocks in that loop, and then then my existing stated would be copied.

**Comment by georglauterbach** [comment] 2022-09-14 12:15
> Ah, I was not aware there was additional state.
> 
> My '/var/mail-state' dir is empty so it seems like I would hit the second of the conditional blocks in that loop, and then then my existing stated would be copied.

Yes :)

**Comment by rhyst** [comment] 2022-09-14 13:59
I did it and nothing bad seems to have happened. I did get the following errors:

```
Sep 14 13:53:45 mail postfix/master[51163]: fatal: open lock file /var/lib/postfix/master.lock: cannot open file: Permission denied
Sep 14 13:53:49 mail amavis[51235]: (!)Net::Server: 2022/09/14-13:53:49 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n  at line 66 in file /usr/share/perl5/Net/Server/Pr
```

But I solved that with `chmod o+x /var/mail-state` so that it looks like:
```
root@mail:/# ls -la /var
...
drwxrwsr-x 9 docker docker 4096 Sep 14 13:10 mail-state
...
```
Thanks!

**Comment by georglauterbach** [comment] 2022-09-14 14:19
Nice! I will close this issue. If there are problems, just reply and we can re-open this issue :)

**Closed by georglauterbach** 2022-09-14 14:19 UTC
Labels: meta/needs triage, meta/help wanted, kind/question, priority/low
