### ISSUE TITLE
bug report: Rspamd DKIM private key permissions warning on startup

### ISSUE THREAD

**Issue by apratasenia** [docker-mailserver/docker-mailserver#4054] opened 2024-06-07 09:09 UTC
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Again having an issue described and fixed [here](https://github.com/docker-mailserver/docker-mailserver/pull/3669) after upgrading from 13.3.1 to 14.0.0

The startup message is:
(Rspamd setup) Rspamd DKIM private key file '/tmp/docker-mailserver/rspamd/dkim/<filiename>.private' does not appear to have correct permissions/ownership for Rspamd to use it

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Fedora CoreOS 40.20240519.3.0

**Comment by georglauterbach** [comment] 2024-06-09 15:22
> `(Rspamd setup) Rspamd DKIM private key file '/tmp/docker-mailserver/rspamd/dkim/.private' does not appear to have correct permissions/ownership for Rspamd to use it`

This seems to indicate the setup procedure may have parsed the configuration wrong. Please post the contents of `/etc/rspamd/local.d/dkim_signing.conf` or `/etc/rspamd/local.d/dkim_signing.conf`, or both if you have both.

**Comment by apratasenia** [comment] 2024-06-10 19:20
@georglauterbach I only have this config:

root@mail:/# cat  /etc/rspamd/override.d/dkim_signing.conf
# documentation: https://rspamd.com/doc/modules/dkim_signing.html

enabled = true;

sign_authenticated = true;
sign_local = true;

use_domain = "header";
use_redis = false; # don't change unless Redis also provides the DKIM keys
use_esld = true;
check_pubkey = true;

domain {
    mydomain.zone {
        path = "/tmp/docker-mailserver/rspamd/dkim/<filename>.private";
        selector = "dkim1";
    }
}

**Comment by georglauterbach** [comment] 2024-06-10 20:22
You seem to have anonymised `<filename>`; this was not only not necessary (this is not important information), I actually need to know exactly this line for investigations. Hence, please tell me what `<filename>` really is.

**Comment by apratasenia** [comment] 2024-06-11 08:26
@georglauterbach 
<filename>= mydomain.zone, i.e. the whole domain part is the following:

```
domain {
    mydomain.zone {
        path = "/tmp/docker-mailserver/rspamd/dkim/mydomain.zone.private";
        selector = "dkim1";
    }
}

```

**Comment by georglauterbach** [comment] 2024-06-11 14:41
Thanks! I will check the logic later and report back.

**Comment by some-user123** [comment] 2024-06-11 19:27
I'm experiencing the same issue (also no `local.d`, but only `override.d/dkim_signing.conf`.

For me it helped as a workaround to set permissions of `*.private.txt` to `644`  instead of `640`.

**Comment by georglauterbach** [comment] 2024-06-11 21:40
Our script should be parsing this file correctly. Can you use `LOG_LEVEL=trace` and provide the Rspamd-related log? I am looking for a line that reads `Checking DKIM file '<FILE>'`.

Please also check whether a hidden file exists in `/tmp/docker-mailserver/rspamd/dkim` by running `ls -lha /tmp/docker-mailserver/rspamd/dkim`.

Please also post the output of `ls -lh /tmp/docker-mailserver/rspamd/dkim/mydomain.zone.private`.

---

@some-user123 please also provide your full `override.d/dkim_signing.conf` and the output of `ls -lh <PATH TO YOUR PRIVATE KEY FILE>`.

**Comment by some-user123** [comment] 2024-06-12 10:44
`override.d/dkim_signing.conf` is the same as above, just with two domains.

After applying `chmod 644`:
``` 
-rw-r--r-- 1 _rspamd _rspamd 1.7K May 16  2024 /tmp/docker-mailserver/rspamd/dkim/rsa-2048-dkim202405-example.com.private.txt
-rw-r--r-- 1 _rspamd _rspamd 1.7K May 10  2024 /tmp/docker-mailserver/rspamd/dkim/rsa-2048-dkim202405-example.net.private.txt
```

No hidden files in `/tmp/docker-mailserver/rspamd/dkim`, just the six files for the two domains. 

I cannot reproduce the error (with/without `LOG_LEVEL=trace`). To me it seems like a one-time error. `chmod 644` wasn't really necessary.

In a backup from before the upgrade to 14.0.0 the files were owned by 113:115. After the update they are owned by 111:114 (_rspamd:_rspamd). I guess this change of ownership was done after the script complained about wrong rights during first start of 14.0.0.

**Comment by apratasenia** [comment] 2024-06-12 15:13
@georglauterbach 

```
root@mail:/# ls -lha /tmp/docker-mailserver/rspamd/dkim
total 8.0K
drwxr-xr-x. 2 _rspamd _rspamd   56 Apr 20  2023 .
drwxr-xr-x. 3 redis   _rspamd   46 Apr  4 12:25 ..
-rw-r-----. 1 _rspamd _rspamd 1.7K Apr 20  2023 mydomain.zone.private
-rw-r--r--. 1 _rspamd _rspamd  452 Apr 20  2023 mydomain.zone.txt

```

```
root@mail:/# ls -nh /tmp/docker-mailserver/rspamd/dkim/mydomain.zone.private
-rw-r-----. 1 111 114 1.7K Apr 20  2023 /tmp/docker-mailserver/rspamd/dkim/mydomain.zone.private
```

I suppose to agree with @some-user123 regarding one-time error, the warning is gone after I restarted the DMS with 
`docker-compose down && docker-sompose up -d`

**Comment by georglauterbach** [comment] 2024-06-13 18:59
I see. This may be a weird bug on our side that only surfaces during the update; I don't really know. I will close this for now; please let me know when it pops back up.

**Closed by georglauterbach** 2024-06-13 18:59 UTC
Labels: meta/needs triage, kind/bug/report
