### ISSUE TITLE
bug report: catch-all takes all incoming emails

### ISSUE THREAD

**Issue by ahshum** [docker-mailserver/docker-mailserver#3408] opened 2023-06-27 18:52 UTC
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

According to the FAQ of [adding a catch-all](https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-can-i-configure-a-catch-all), all incoming emails always go to catch-all no matter there is a real account or other virtual map. That happens to both `postfix-virtual.cf` or `postfix-regexp.cf`.

### 👟 Reproduction Steps

`docker-compose.yaml`
```
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: local.host
    volumes:
      - ./dms/mail-data/:/var/mail/
      - ./dms/config/:/tmp/docker-mailserver/
    restart: always
```

`postfix-main.cf`
```
mydestination = localhost.$mydomain, localhost
```

add accounts
```
setup email add user@local.host
setup email add catchall@local.host
```

`postfix-virtual.cf`
```
virtual@local.host user@local.host
@local.host catchall@local.host
```

Also tried with `postfix-regexp.cf`
```
/^virtual@local.host$/ user@local.host
/^(.*)@local.host$/ catchall@local.host
```

Test sending with
```
sendmail user@local.host <<EOF
subject: test

body
EOF
```

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Debian 11 x86_64, Windows ArchWSL x86_64

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: local.host
    volumes:
      - ./dms/mail-data/:/var/mail/
      - ./dms/config/:/tmp/docker-mailserver/
    restart: always
```

### 📜 Relevant log output

```Text
[   INF   ]  Welcome to docker-mailserver 12.1.0
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[ WARNING ]  !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
[ WARNING ]  'ONE_DIR=1' but no volume was mounted to '/var/mail-state'
[   INF   ]  Starting daemons
[   INF   ]  local.host is up and running
Jun 27 18:50:39 local amavis[519]: starting. /usr/sbin/amavisd-new at local.host amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Jun 27 18:50:39 local amavis[519]: perl=5.032001, user=, EUID: 109 (109);  group=, EGID: 111 111 (111 111)
Jun 27 18:50:39 local amavis[519]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'
Jun 27 18:50:39 local amavis[519]: Net::Server: User Not Defined.  Defaulting to EUID '109'
Jun 27 18:50:39 local amavis[519]: No ext program for   .zoo, tried: zoo
Jun 27 18:50:39 local amavis[519]: No ext program for   .doc, tried: ripole
Jun 27 18:50:39 local amavis[519]: No decoder for       .F
Jun 27 18:50:39 local amavis[519]: No decoder for       .doc
Jun 27 18:50:39 local amavis[519]: No decoder for       .zoo
Jun 27 18:50:57 local postfix/pickup[581]: 7BFF7C6CBE: uid=0 from=<root>
Jun 27 18:50:57 local postfix/cleanup[665]: 7BFF7C6CBE: message-id=<20230627185057.7BFF7C6CBE@local.host>
Jun 27 18:50:57 local opendkim[452]: 7BFF7C6CBE: localhost [127.0.0.1] not internal
Jun 27 18:50:57 local opendkim[452]: 7BFF7C6CBE: not authenticated
Jun 27 18:50:57 local opendkim[452]: 7BFF7C6CBE: no signature data
Jun 27 18:50:57 local postfix/qmgr[582]: 7BFF7C6CBE: from=<root@local.host>, size=293, nrcpt=1 (queue active)
Jun 27 18:50:57 local dovecot: lmtp(668): Connect from local
Jun 27 18:50:57 local dovecot: lmtp(catchall@local.host)<668><E/mYIZEvm2ScAgAAOoqd4A>: Error: Mailbox INBOX: mmap(size=0) failed with file /var/mail/local.host/catchall/dovecot.index.cache: No such file or directory
Jun 27 18:50:57 local dovecot: lmtp(catchall@local.host)<668><E/mYIZEvm2ScAgAAOoqd4A>: sieve: msgid=<20230627185057.7BFF7C6CBE@local.host>: stored mail into mailbox 'INBOX'
Jun 27 18:50:57 local postfix/lmtp[667]: 7BFF7C6CBE: to=<catchall@local.host>, orig_to=<user@local.host>, relay=local.host[/var/run/dovecot/lmtp], delay=0.43, delays=0.05/0.01/0.02/0.35, dsn=2.0.0, status=sent (250 2.0.0 <catchall@local.host> E/mYIZEvm2ScAgAAOoqd4A Saved)
Jun 27 18:50:57 local dovecot: lmtp(668): Disconnect from local: Logged out (state=READY)
Jun 27 18:50:57 local postfix/qmgr[582]: 7BFF7C6CBE: removed
```

**Comment by polarathene** [comment] 2023-06-28 01:28
Not a bug. Virtual aliases will have priority, and a wildcard / catch-all will be a match.

If no match, then the actual accounts are checked against `mydestination` domain part (_typically a system account like `clamav` or `amavis`_), or an account managed by Dovecot (_populated by our `postfix-accounts.cf`_).

---

Closing as [this is a duplicate issue](https://github.com/docker-mailserver/docker-mailserver/issues/3022#issuecomment-1610452561). Someone will need to look into and contribute managing a catch-all address for `virtual_mailbox_maps` instead of `virtual_alias_maps` (Postfix `main.cf` settings), where catch-all addresses are managed via a separate config file to ensure they're only matched against after the real accounts have been (_first match wins otherwise_).

Alternative workaround might be to create an alias of the real account to the real account.

**Closed** 2023-06-28 01:28 UTC
Labels: meta/needs triage, kind/bug/report
